#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="hoteldb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertuser(user instance);
    partial void Updateuser(user instance);
    partial void Deleteuser(user instance);
    partial void Insertroom(room instance);
    partial void Updateroom(room instance);
    partial void Deleteroom(room instance);
    partial void Insertcheckin(checkin instance);
    partial void Updatecheckin(checkin instance);
    partial void Deletecheckin(checkin instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::HotelManagementSystem.Properties.Settings.Default.hotel_management_systemdb, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<room> rooms
		{
			get
			{
				return this.GetTable<room>();
			}
		}
		
		public System.Data.Linq.Table<checkin> checkins
		{
			get
			{
				return this.GetTable<checkin>();
			}
		}
		
		public System.Data.Linq.Table<userlog> userlogs
		{
			get
			{
				return this.GetTable<userlog>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listview_users")]
		public ISingleResult<listview_usersResult> listview_users()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listview_usersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.user_login")]
		public ISingleResult<user_loginResult> user_login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string users_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string users_password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), users_name, users_password);
			return ((ISingleResult<user_loginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_save")]
		public int room_save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> room_num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string room_type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string room_rate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string room_remarks)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), room_num, room_type, room_rate, room_remarks);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_disp")]
		public ISingleResult<room_dispResult> room_disp()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<room_dispResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_update")]
		public int room_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> room_num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string room_type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string room_rate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), room_num, room_type, room_rate);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_delete")]
		public int room_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> room_num)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), room_num);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_search")]
		public ISingleResult<room_searchResult> room_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<room_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkin_room_update")]
		public int checkin_room_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> room_num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string room_remarks)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), room_num, room_remarks);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkin_save")]
		public int checkin_save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string guest_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> room_num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkindate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkoutdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string noofdays, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string subtotal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string adpayment, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string balance, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string checkin_status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), guest_name, room_num, checkindate, checkoutdate, noofdays, subtotal, adpayment, balance, checkin_status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkout_disp_search")]
		public ISingleResult<checkout_disp_searchResult> checkout_disp_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string key)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), key);
			return ((ISingleResult<checkout_disp_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkout_disp")]
		public ISingleResult<checkout_dispResult> checkout_disp()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<checkout_dispResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkin_update")]
		public int checkin_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> room_num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> checkoutdate, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string noofdays, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string subtotal, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string balance, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string checkin_status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), room_num, checkoutdate, noofdays, subtotal, balance, checkin_status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.room_checkout")]
		public int room_checkout([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> room_num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string room_remarks)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), room_num, room_remarks);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.checkout_List")]
		public ISingleResult<checkout_ListResult> checkout_List()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<checkout_ListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_logs")]
		public int sp_logs([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string logss)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), logss);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.logs_display")]
		public ISingleResult<logs_displayResult> logs_display()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<logs_displayResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.reservation_List")]
		public ISingleResult<reservation_ListResult> reservation_List()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<reservation_ListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.reserve_checkin")]
		public int reserve_checkin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> room_num, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string checkin_status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), room_num, checkin_status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sales_rep")]
		public ISingleResult<sales_repResult> sales_rep()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sales_repResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sales_report")]
		public ISingleResult<sales_reportResult> sales_report()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sales_reportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.save_user")]
		public int save_user([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string users_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string position, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string users_password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), users_name, position, users_password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.user_update")]
		public int user_update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string users_name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string position, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string users_password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, users_name, position, users_password);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.user_delete")]
		public int user_delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.user_disp")]
		public ISingleResult<user_dispResult> user_disp()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<user_dispResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _users_name;
		
		private string _position;
		
		private string _users_password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onusers_nameChanging(string value);
    partial void Onusers_nameChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void Onusers_passwordChanging(string value);
    partial void Onusers_passwordChanged();
    #endregion
		
		public user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string users_name
		{
			get
			{
				return this._users_name;
			}
			set
			{
				if ((this._users_name != value))
				{
					this.Onusers_nameChanging(value);
					this.SendPropertyChanging();
					this._users_name = value;
					this.SendPropertyChanged("users_name");
					this.Onusers_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_password", DbType="VarChar(50)")]
		public string users_password
		{
			get
			{
				return this._users_password;
			}
			set
			{
				if ((this._users_password != value))
				{
					this.Onusers_passwordChanging(value);
					this.SendPropertyChanging();
					this._users_password = value;
					this.SendPropertyChanged("users_password");
					this.Onusers_passwordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.room")]
	public partial class room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _room_id;
		
		private System.Nullable<int> _room_num;
		
		private string _room_type;
		
		private string _room_rate;
		
		private string _room_remarks;
		
		private EntitySet<checkin> _checkins;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onroom_idChanging(int value);
    partial void Onroom_idChanged();
    partial void Onroom_numChanging(System.Nullable<int> value);
    partial void Onroom_numChanged();
    partial void Onroom_typeChanging(string value);
    partial void Onroom_typeChanged();
    partial void Onroom_rateChanging(string value);
    partial void Onroom_rateChanged();
    partial void Onroom_remarksChanging(string value);
    partial void Onroom_remarksChanged();
    #endregion
		
		public room()
		{
			this._checkins = new EntitySet<checkin>(new Action<checkin>(this.attach_checkins), new Action<checkin>(this.detach_checkins));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int room_id
		{
			get
			{
				return this._room_id;
			}
			set
			{
				if ((this._room_id != value))
				{
					this.Onroom_idChanging(value);
					this.SendPropertyChanging();
					this._room_id = value;
					this.SendPropertyChanged("room_id");
					this.Onroom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_num", DbType="Int")]
		public System.Nullable<int> room_num
		{
			get
			{
				return this._room_num;
			}
			set
			{
				if ((this._room_num != value))
				{
					this.Onroom_numChanging(value);
					this.SendPropertyChanging();
					this._room_num = value;
					this.SendPropertyChanged("room_num");
					this.Onroom_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_type", DbType="VarChar(50)")]
		public string room_type
		{
			get
			{
				return this._room_type;
			}
			set
			{
				if ((this._room_type != value))
				{
					this.Onroom_typeChanging(value);
					this.SendPropertyChanging();
					this._room_type = value;
					this.SendPropertyChanged("room_type");
					this.Onroom_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_rate", DbType="VarChar(50)")]
		public string room_rate
		{
			get
			{
				return this._room_rate;
			}
			set
			{
				if ((this._room_rate != value))
				{
					this.Onroom_rateChanging(value);
					this.SendPropertyChanging();
					this._room_rate = value;
					this.SendPropertyChanged("room_rate");
					this.Onroom_rateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_remarks", DbType="VarChar(50)")]
		public string room_remarks
		{
			get
			{
				return this._room_remarks;
			}
			set
			{
				if ((this._room_remarks != value))
				{
					this.Onroom_remarksChanging(value);
					this.SendPropertyChanging();
					this._room_remarks = value;
					this.SendPropertyChanged("room_remarks");
					this.Onroom_remarksChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="room_checkin", Storage="_checkins", ThisKey="room_num", OtherKey="room_num")]
		public EntitySet<checkin> checkins
		{
			get
			{
				return this._checkins;
			}
			set
			{
				this._checkins.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_checkins(checkin entity)
		{
			this.SendPropertyChanging();
			entity.room = this;
		}
		
		private void detach_checkins(checkin entity)
		{
			this.SendPropertyChanging();
			entity.room = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.checkin")]
	public partial class checkin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _transact_id;
		
		private string _guest_name;
		
		private System.Nullable<int> _room_num;
		
		private System.Nullable<System.DateTime> _checkindate;
		
		private System.Nullable<System.DateTime> _checkoutdate;
		
		private string _noofdays;
		
		private string _subtotal;
		
		private string _adpayment;
		
		private string _balance;
		
		private string _checkin_status;
		
		private EntityRef<room> _room;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontransact_idChanging(int value);
    partial void Ontransact_idChanged();
    partial void Onguest_nameChanging(string value);
    partial void Onguest_nameChanged();
    partial void Onroom_numChanging(System.Nullable<int> value);
    partial void Onroom_numChanged();
    partial void OncheckindateChanging(System.Nullable<System.DateTime> value);
    partial void OncheckindateChanged();
    partial void OncheckoutdateChanging(System.Nullable<System.DateTime> value);
    partial void OncheckoutdateChanged();
    partial void OnnoofdaysChanging(string value);
    partial void OnnoofdaysChanged();
    partial void OnsubtotalChanging(string value);
    partial void OnsubtotalChanged();
    partial void OnadpaymentChanging(string value);
    partial void OnadpaymentChanged();
    partial void OnbalanceChanging(string value);
    partial void OnbalanceChanged();
    partial void Oncheckin_statusChanging(string value);
    partial void Oncheckin_statusChanged();
    #endregion
		
		public checkin()
		{
			this._room = default(EntityRef<room>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transact_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int transact_id
		{
			get
			{
				return this._transact_id;
			}
			set
			{
				if ((this._transact_id != value))
				{
					this.Ontransact_idChanging(value);
					this.SendPropertyChanging();
					this._transact_id = value;
					this.SendPropertyChanged("transact_id");
					this.Ontransact_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_name", DbType="VarChar(50)")]
		public string guest_name
		{
			get
			{
				return this._guest_name;
			}
			set
			{
				if ((this._guest_name != value))
				{
					this.Onguest_nameChanging(value);
					this.SendPropertyChanging();
					this._guest_name = value;
					this.SendPropertyChanged("guest_name");
					this.Onguest_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_num", DbType="Int")]
		public System.Nullable<int> room_num
		{
			get
			{
				return this._room_num;
			}
			set
			{
				if ((this._room_num != value))
				{
					if (this._room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onroom_numChanging(value);
					this.SendPropertyChanging();
					this._room_num = value;
					this.SendPropertyChanged("room_num");
					this.Onroom_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkindate", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkindate
		{
			get
			{
				return this._checkindate;
			}
			set
			{
				if ((this._checkindate != value))
				{
					this.OncheckindateChanging(value);
					this.SendPropertyChanging();
					this._checkindate = value;
					this.SendPropertyChanged("checkindate");
					this.OncheckindateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkoutdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkoutdate
		{
			get
			{
				return this._checkoutdate;
			}
			set
			{
				if ((this._checkoutdate != value))
				{
					this.OncheckoutdateChanging(value);
					this.SendPropertyChanging();
					this._checkoutdate = value;
					this.SendPropertyChanged("checkoutdate");
					this.OncheckoutdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noofdays", DbType="VarChar(50)")]
		public string noofdays
		{
			get
			{
				return this._noofdays;
			}
			set
			{
				if ((this._noofdays != value))
				{
					this.OnnoofdaysChanging(value);
					this.SendPropertyChanging();
					this._noofdays = value;
					this.SendPropertyChanged("noofdays");
					this.OnnoofdaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="VarChar(50)")]
		public string subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this.OnsubtotalChanging(value);
					this.SendPropertyChanging();
					this._subtotal = value;
					this.SendPropertyChanged("subtotal");
					this.OnsubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adpayment", DbType="VarChar(50)")]
		public string adpayment
		{
			get
			{
				return this._adpayment;
			}
			set
			{
				if ((this._adpayment != value))
				{
					this.OnadpaymentChanging(value);
					this.SendPropertyChanging();
					this._adpayment = value;
					this.SendPropertyChanged("adpayment");
					this.OnadpaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="VarChar(50)")]
		public string balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this.OnbalanceChanging(value);
					this.SendPropertyChanging();
					this._balance = value;
					this.SendPropertyChanged("balance");
					this.OnbalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkin_status", DbType="VarChar(50)")]
		public string checkin_status
		{
			get
			{
				return this._checkin_status;
			}
			set
			{
				if ((this._checkin_status != value))
				{
					this.Oncheckin_statusChanging(value);
					this.SendPropertyChanging();
					this._checkin_status = value;
					this.SendPropertyChanged("checkin_status");
					this.Oncheckin_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="room_checkin", Storage="_room", ThisKey="room_num", OtherKey="room_num", IsForeignKey=true)]
		public room room
		{
			get
			{
				return this._room.Entity;
			}
			set
			{
				room previousValue = this._room.Entity;
				if (((previousValue != value) 
							|| (this._room.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._room.Entity = null;
						previousValue.checkins.Remove(this);
					}
					this._room.Entity = value;
					if ((value != null))
					{
						value.checkins.Add(this);
						this._room_num = value.room_num;
					}
					else
					{
						this._room_num = default(Nullable<int>);
					}
					this.SendPropertyChanged("room");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userlogs")]
	public partial class userlog
	{
		
		private int _logs_id;
		
		private string _logss;
		
		private System.Nullable<System.DateTime> _datetimes;
		
		public userlog()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logs_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int logs_id
		{
			get
			{
				return this._logs_id;
			}
			set
			{
				if ((this._logs_id != value))
				{
					this._logs_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logss", DbType="VarChar(50)")]
		public string logss
		{
			get
			{
				return this._logss;
			}
			set
			{
				if ((this._logss != value))
				{
					this._logss = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datetimes", DbType="DateTime")]
		public System.Nullable<System.DateTime> datetimes
		{
			get
			{
				return this._datetimes;
			}
			set
			{
				if ((this._datetimes != value))
				{
					this._datetimes = value;
				}
			}
		}
	}
	
	public partial class listview_usersResult
	{
		
		private string _position;
		
		private string _users_name;
		
		public listview_usersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this._position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string users_name
		{
			get
			{
				return this._users_name;
			}
			set
			{
				if ((this._users_name != value))
				{
					this._users_name = value;
				}
			}
		}
	}
	
	public partial class user_loginResult
	{
		
		private int _id;
		
		private string _users_name;
		
		private string _position;
		
		private string _users_password;
		
		public user_loginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string users_name
		{
			get
			{
				return this._users_name;
			}
			set
			{
				if ((this._users_name != value))
				{
					this._users_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this._position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_password", DbType="VarChar(50)")]
		public string users_password
		{
			get
			{
				return this._users_password;
			}
			set
			{
				if ((this._users_password != value))
				{
					this._users_password = value;
				}
			}
		}
	}
	
	public partial class room_dispResult
	{
		
		private System.Nullable<int> _room_num;
		
		private string _room_type;
		
		private string _room_rate;
		
		private string _room_remarks;
		
		public room_dispResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_num", DbType="Int")]
		public System.Nullable<int> room_num
		{
			get
			{
				return this._room_num;
			}
			set
			{
				if ((this._room_num != value))
				{
					this._room_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_type", DbType="VarChar(50)")]
		public string room_type
		{
			get
			{
				return this._room_type;
			}
			set
			{
				if ((this._room_type != value))
				{
					this._room_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_rate", DbType="VarChar(50)")]
		public string room_rate
		{
			get
			{
				return this._room_rate;
			}
			set
			{
				if ((this._room_rate != value))
				{
					this._room_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_remarks", DbType="VarChar(50)")]
		public string room_remarks
		{
			get
			{
				return this._room_remarks;
			}
			set
			{
				if ((this._room_remarks != value))
				{
					this._room_remarks = value;
				}
			}
		}
	}
	
	public partial class room_searchResult
	{
		
		private int _room_id;
		
		private System.Nullable<int> _room_num;
		
		private string _room_type;
		
		private string _room_rate;
		
		private string _room_remarks;
		
		public room_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_id", DbType="Int NOT NULL")]
		public int room_id
		{
			get
			{
				return this._room_id;
			}
			set
			{
				if ((this._room_id != value))
				{
					this._room_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_num", DbType="Int")]
		public System.Nullable<int> room_num
		{
			get
			{
				return this._room_num;
			}
			set
			{
				if ((this._room_num != value))
				{
					this._room_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_type", DbType="VarChar(50)")]
		public string room_type
		{
			get
			{
				return this._room_type;
			}
			set
			{
				if ((this._room_type != value))
				{
					this._room_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_rate", DbType="VarChar(50)")]
		public string room_rate
		{
			get
			{
				return this._room_rate;
			}
			set
			{
				if ((this._room_rate != value))
				{
					this._room_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_remarks", DbType="VarChar(50)")]
		public string room_remarks
		{
			get
			{
				return this._room_remarks;
			}
			set
			{
				if ((this._room_remarks != value))
				{
					this._room_remarks = value;
				}
			}
		}
	}
	
	public partial class checkout_disp_searchResult
	{
		
		private int _transact_id;
		
		private string _guest_name;
		
		private System.Nullable<int> _room_num;
		
		private string _room_type;
		
		private string _room_rate;
		
		private System.Nullable<System.DateTime> _checkindate;
		
		private string _subtotal;
		
		private string _adpayment;
		
		private string _balance;
		
		public checkout_disp_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transact_id", DbType="Int NOT NULL")]
		public int transact_id
		{
			get
			{
				return this._transact_id;
			}
			set
			{
				if ((this._transact_id != value))
				{
					this._transact_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_name", DbType="VarChar(50)")]
		public string guest_name
		{
			get
			{
				return this._guest_name;
			}
			set
			{
				if ((this._guest_name != value))
				{
					this._guest_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_num", DbType="Int")]
		public System.Nullable<int> room_num
		{
			get
			{
				return this._room_num;
			}
			set
			{
				if ((this._room_num != value))
				{
					this._room_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_type", DbType="VarChar(50)")]
		public string room_type
		{
			get
			{
				return this._room_type;
			}
			set
			{
				if ((this._room_type != value))
				{
					this._room_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_rate", DbType="VarChar(50)")]
		public string room_rate
		{
			get
			{
				return this._room_rate;
			}
			set
			{
				if ((this._room_rate != value))
				{
					this._room_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkindate", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkindate
		{
			get
			{
				return this._checkindate;
			}
			set
			{
				if ((this._checkindate != value))
				{
					this._checkindate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="VarChar(50)")]
		public string subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this._subtotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adpayment", DbType="VarChar(50)")]
		public string adpayment
		{
			get
			{
				return this._adpayment;
			}
			set
			{
				if ((this._adpayment != value))
				{
					this._adpayment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="VarChar(50)")]
		public string balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this._balance = value;
				}
			}
		}
	}
	
	public partial class checkout_dispResult
	{
		
		private int _transact_id;
		
		private string _guest_name;
		
		private System.Nullable<int> _room_num;
		
		private string _room_type;
		
		private string _room_rate;
		
		private System.Nullable<System.DateTime> _checkindate;
		
		private string _subtotal;
		
		private string _adpayment;
		
		private string _balance;
		
		public checkout_dispResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transact_id", DbType="Int NOT NULL")]
		public int transact_id
		{
			get
			{
				return this._transact_id;
			}
			set
			{
				if ((this._transact_id != value))
				{
					this._transact_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_name", DbType="VarChar(50)")]
		public string guest_name
		{
			get
			{
				return this._guest_name;
			}
			set
			{
				if ((this._guest_name != value))
				{
					this._guest_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_num", DbType="Int")]
		public System.Nullable<int> room_num
		{
			get
			{
				return this._room_num;
			}
			set
			{
				if ((this._room_num != value))
				{
					this._room_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_type", DbType="VarChar(50)")]
		public string room_type
		{
			get
			{
				return this._room_type;
			}
			set
			{
				if ((this._room_type != value))
				{
					this._room_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_rate", DbType="VarChar(50)")]
		public string room_rate
		{
			get
			{
				return this._room_rate;
			}
			set
			{
				if ((this._room_rate != value))
				{
					this._room_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkindate", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkindate
		{
			get
			{
				return this._checkindate;
			}
			set
			{
				if ((this._checkindate != value))
				{
					this._checkindate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="VarChar(50)")]
		public string subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this._subtotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adpayment", DbType="VarChar(50)")]
		public string adpayment
		{
			get
			{
				return this._adpayment;
			}
			set
			{
				if ((this._adpayment != value))
				{
					this._adpayment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="VarChar(50)")]
		public string balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this._balance = value;
				}
			}
		}
	}
	
	public partial class checkout_ListResult
	{
		
		private int _transact_id;
		
		private string _guest_name;
		
		private System.Nullable<int> _room_num;
		
		private string _room_type;
		
		private string _room_rate;
		
		private System.Nullable<System.DateTime> _checkindate;
		
		private System.Nullable<System.DateTime> _checkoutdate;
		
		private string _subtotal;
		
		public checkout_ListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transact_id", DbType="Int NOT NULL")]
		public int transact_id
		{
			get
			{
				return this._transact_id;
			}
			set
			{
				if ((this._transact_id != value))
				{
					this._transact_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_name", DbType="VarChar(50)")]
		public string guest_name
		{
			get
			{
				return this._guest_name;
			}
			set
			{
				if ((this._guest_name != value))
				{
					this._guest_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_num", DbType="Int")]
		public System.Nullable<int> room_num
		{
			get
			{
				return this._room_num;
			}
			set
			{
				if ((this._room_num != value))
				{
					this._room_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_type", DbType="VarChar(50)")]
		public string room_type
		{
			get
			{
				return this._room_type;
			}
			set
			{
				if ((this._room_type != value))
				{
					this._room_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_rate", DbType="VarChar(50)")]
		public string room_rate
		{
			get
			{
				return this._room_rate;
			}
			set
			{
				if ((this._room_rate != value))
				{
					this._room_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkindate", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkindate
		{
			get
			{
				return this._checkindate;
			}
			set
			{
				if ((this._checkindate != value))
				{
					this._checkindate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkoutdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkoutdate
		{
			get
			{
				return this._checkoutdate;
			}
			set
			{
				if ((this._checkoutdate != value))
				{
					this._checkoutdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="VarChar(50)")]
		public string subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this._subtotal = value;
				}
			}
		}
	}
	
	public partial class logs_displayResult
	{
		
		private int _Log_id;
		
		private string _Information;
		
		private System.Nullable<System.DateTime> _DateLog;
		
		public logs_displayResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Log_id", DbType="Int NOT NULL")]
		public int Log_id
		{
			get
			{
				return this._Log_id;
			}
			set
			{
				if ((this._Log_id != value))
				{
					this._Log_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Information", DbType="VarChar(50)")]
		public string Information
		{
			get
			{
				return this._Information;
			}
			set
			{
				if ((this._Information != value))
				{
					this._Information = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLog", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateLog
		{
			get
			{
				return this._DateLog;
			}
			set
			{
				if ((this._DateLog != value))
				{
					this._DateLog = value;
				}
			}
		}
	}
	
	public partial class reservation_ListResult
	{
		
		private int _transact_id;
		
		private string _guest_name;
		
		private System.Nullable<int> _room_num;
		
		private string _room_type;
		
		private string _room_rate;
		
		private System.Nullable<System.DateTime> _checkindate;
		
		private System.Nullable<System.DateTime> _checkoutdate;
		
		private string _noofdays;
		
		private string _subtotal;
		
		private string _adpayment;
		
		private string _balance;
		
		public reservation_ListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transact_id", DbType="Int NOT NULL")]
		public int transact_id
		{
			get
			{
				return this._transact_id;
			}
			set
			{
				if ((this._transact_id != value))
				{
					this._transact_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guest_name", DbType="VarChar(50)")]
		public string guest_name
		{
			get
			{
				return this._guest_name;
			}
			set
			{
				if ((this._guest_name != value))
				{
					this._guest_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_num", DbType="Int")]
		public System.Nullable<int> room_num
		{
			get
			{
				return this._room_num;
			}
			set
			{
				if ((this._room_num != value))
				{
					this._room_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_type", DbType="VarChar(50)")]
		public string room_type
		{
			get
			{
				return this._room_type;
			}
			set
			{
				if ((this._room_type != value))
				{
					this._room_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room_rate", DbType="VarChar(50)")]
		public string room_rate
		{
			get
			{
				return this._room_rate;
			}
			set
			{
				if ((this._room_rate != value))
				{
					this._room_rate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkindate", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkindate
		{
			get
			{
				return this._checkindate;
			}
			set
			{
				if ((this._checkindate != value))
				{
					this._checkindate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_checkoutdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> checkoutdate
		{
			get
			{
				return this._checkoutdate;
			}
			set
			{
				if ((this._checkoutdate != value))
				{
					this._checkoutdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noofdays", DbType="VarChar(50)")]
		public string noofdays
		{
			get
			{
				return this._noofdays;
			}
			set
			{
				if ((this._noofdays != value))
				{
					this._noofdays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal", DbType="VarChar(50)")]
		public string subtotal
		{
			get
			{
				return this._subtotal;
			}
			set
			{
				if ((this._subtotal != value))
				{
					this._subtotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adpayment", DbType="VarChar(50)")]
		public string adpayment
		{
			get
			{
				return this._adpayment;
			}
			set
			{
				if ((this._adpayment != value))
				{
					this._adpayment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_balance", DbType="VarChar(50)")]
		public string balance
		{
			get
			{
				return this._balance;
			}
			set
			{
				if ((this._balance != value))
				{
					this._balance = value;
				}
			}
		}
	}
	
	public partial class sales_repResult
	{
		
		private string _DaySales;
		
		private System.Nullable<decimal> _PAYMENT;
		
		public sales_repResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaySales", DbType="NVarChar(MAX)")]
		public string DaySales
		{
			get
			{
				return this._DaySales;
			}
			set
			{
				if ((this._DaySales != value))
				{
					this._DaySales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENT", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> PAYMENT
		{
			get
			{
				return this._PAYMENT;
			}
			set
			{
				if ((this._PAYMENT != value))
				{
					this._PAYMENT = value;
				}
			}
		}
	}
	
	public partial class sales_reportResult
	{
		
		private string _DaySales;
		
		private System.Nullable<decimal> _PAYMENT;
		
		public sales_reportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaySales", DbType="NVarChar(MAX)")]
		public string DaySales
		{
			get
			{
				return this._DaySales;
			}
			set
			{
				if ((this._DaySales != value))
				{
					this._DaySales = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAYMENT", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> PAYMENT
		{
			get
			{
				return this._PAYMENT;
			}
			set
			{
				if ((this._PAYMENT != value))
				{
					this._PAYMENT = value;
				}
			}
		}
	}
	
	public partial class user_dispResult
	{
		
		private int _id;
		
		private string _users_name;
		
		private string _position;
		
		private string _users_password;
		
		public user_dispResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string users_name
		{
			get
			{
				return this._users_name;
			}
			set
			{
				if ((this._users_name != value))
				{
					this._users_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this._position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_users_password", DbType="VarChar(50)")]
		public string users_password
		{
			get
			{
				return this._users_password;
			}
			set
			{
				if ((this._users_password != value))
				{
					this._users_password = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
